version: "2"

services:
  php:
    image: xlogical:wxwork-message-audit
    container_name: messageaudit.docker.internal
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./:/wxwork-message-audit
    working_dir: /wxwork-message-audit
    entrypoint: [ "/usr/local/bin/php", "artisan", "schedule:work" ]
